blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    #path('<int:pk>/', views.single_post_page),
    #path('', views.index),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about_me/', views.about_me),
    path('',views.landing),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/cateogry/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

single_pages/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category


class PostList(ListView):
    model = Post
    ordering = '-pk'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context


class PostDetail(DetailView):
    model = Post


def single_post_page(request, pk):
    post = Post.objects.get(pk=pk)

    return render(
        request,
        'blog/single_post_page.html',
        {
            'post': post,
        }
    )

def category_page(request, slug):
    if slug == 'no_category':
        category ='미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list' : post_list,
            'categories' : Category.objects.all(),
            'no_category_post_count' : Post.objects.filter(category=None).count(),
            'category' : category,
        }
    )

single_pages/views.py
from django.shortcuts import render

def landing(request):
    return render(
        request,
        'single_pages/landing.html'
    )

def about_me(request):
    return render(
        request,
        'single_pages/about_me.html'
    )

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link rel = 'stylesheet' href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
    </head>
    <body>
        {% include 'blog/navbar.html' %}

        <!-- 본문 영역 -->
        <div class="container my-3">
          <div class="row">
            <div class="col-md-8 col-lg-9" id="main-area">

              {% block main_area %}
              {% endblock %}

            </div>
            <div class="col-md-4 col-lg-3">
               <!-- Search widget-->
               <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
              <!-- Categories widget-->
              <div class="card mb-4" id="categories-card">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <ul>
                            {% for category in categories %}
                            <li>
                                    <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                            </li>
                            {% endfor %}
                            <li>
                                <a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                            </li>
                        </ul>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {% include 'blog/footer.html' %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

        <script src="https://kit.fontawesome.com/d050873185.js" crossorigin="anonymous"></script>
    </body>
</html>

blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>

{% for p in posts %}
    <hr/>
    <h2><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h2>
    <h4>{{ p.created_at }}</h4>
    <p>{{ p.content }}</p>
{% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
        <!--부트스트랩에서 가져온 코드 -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <a class="navbar-brand" href="/">Cat</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/blog/">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About Me</a>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
              <!-- 로그인 버튼 -->
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <!-- Modal -->
        <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="loginModalLabel"><i class="fa-solid fa-right-to-bracket"></i> &nbsp; Log In</h1>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

                <div class="row">
                  <div class="col-md-6">
                    <button type="button" class="btn btn-outline-secondary btn-block btn-sm"><i class="fa-brands fa-google"></i> &nbsp; Log in with Google</button>
                    <button type="button" class="btn btn-outline-secondary btn-block btn-sm"><i class="fa-regular fa-envelope"></i> &nbsp; Log in with E-mail</button>
                  </div>
                  <div class="col-md-6">
                    <button type="button" class="btn btn-outline-secondary btn-block btn-sm"><i class="fa-regular fa-envelope"></i> &nbsp; Sign Up with E-mail</button>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}

                <div id="post-area"><!--포스트 영역-->
                    {% if post.category %}
                        <span class="badge badge-secondary float-right">{{ post.category }}</span>
                     {% else %}
                        <span class="badge badge-secondary float-right">미분류 </span>
                     {% endif %}
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                            <h5 class="text-muted">{{ post.hook_text }}</h5>
                            <!-- Author -->
                            <p class="lead">
                                by
                                <a href="#">{{ post.author | upper }}</a>
                            </p>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{ post.create_at }}</div>
                            <hr>
                        </header>
                        <!-- Preview image figure-->
                        {% if post.head_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image" /></figure>
                        {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/800/200" alt="random_image">
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p>{{ post.content }}</p>

                            <!--태그-->
                            {% if post.tags.exists %}
                                <i class="fa-solid fa-tag"></i>
                                {% for tag in post.tags.iterator %}
                                    <a href="{{ tag.get_absolute_url }}">
                                    <span class="badge rounded-pill text-bg-success">{{ tag }}</span>
                                {% endfor %}
                                <br/>
                                <br/>
                            {% endif %}
                            
                            {% if post.file_upload %}
                              <a href="{{ post.file_upload.url }}" class="btn btn-outline-secondary" role="button">Download:

                                {% if post.get_file_ext == 'csv' %}
                                    <i class="fa-solid fa-file-csv"></i>
                                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                    <i class="fa-solid fa-file-excel"></i>
                                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'docx' %}
                                    <i class="fa-solid fa-file-word"></i>
                                {% else %}
                                    <i class="fa-solid fa-file"></i>
                                {% endif %}
                                {{ post.get_file_name }}
                              </a>
                            {% endif %}
                        </section>
                    </article>
                </div>

                <div id="comment-area"><!--댓글 영역 -->
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}
        <h1>Blog {% if category %}<span class="badge text-bg-secondary">{{ category }}</span>{% endif %}</h1>

        {% if post_list.exists %}

          <!-- Featured blog post-->
          {% for p in post_list %}
          <!-- Blog Post -->
          <div class="card mb-4" id="post-{{ p.pk }}">
            {% if p.head_image %}
              <a href="#!"><img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head im-age" /></a>
            {% else %}
              <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/800/200" alt="random_image">
            {% endif %}
            <div class="card-body">
                {% if p.category %}
                  <span class="badge badge-secondary float-right">{{ p.category }}</span>
                {% else %}
                  <span class="badge badge-secondary float-right">미분류 </span>
                {% endif %}
                <div class="small text-muted">January 1, 2022</div>
                <h2 class="card-title">{{ p.title }}</h2>
                {% if p.hook_text %}
                  <h5 class="text-muted">{{ p.hook_text }}</h5>
                {% endif %}
                <p class="card-text">{{ p.content | truncatewords:45 }}</p>
                <a class="btn btn-primary" href="{{ p.get_absolute_url }}">Read more →</a>
            </div>
            <div class = "card-footer text-muted">
                Posted on {{ p.created_at }} by
                <a href="#">{{ p.author | upper }}</a>
            </div>
          </div>
          {% endfor %}
        {% else %}
          <h3>아직 게시물이 없습니다</h3>
        {% endif %}

    <!-- Pagination-->
    <nav aria-label="Pagination">
      <hr class="my-0" />
      <ul class="pagination justify-content-center my-4">
          <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
          <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
          <li class="page-item"><a class="page-link" href="#!">2</a></li>
          <li class="page-item"><a class="page-link" href="#!">3</a></li>
          <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
          <li class="page-item"><a class="page-link" href="#!">15</a></li>
          <li class="page-item"><a class="page-link" href="#!">Older</a></li>
      </ul>
{% endblock %}

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }} - Blog</title>
</head>
<body>
<nav>
  <a href="/blog/">Blog</a>
</nav>
<h1>{{ post.title }}</h1>
<h4>{{ post.created_at }}</h4>
<p>{{ post.content }}</p>
<hr/>
<h3>여기 댓글이 들어올 수 있겠죠?</h3>
</body>
</html>

single_pages/templates/single_pages/about_me.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>개발자 김수영입니다.</title>
</head>
<body>
<nav>
  <a href="/blog/">Blog</a>
  <a href="/about_me/">About me</a>
</nav>

<h1>안녕하세요. 김수영입니다.</h1>
<h2>이력</h2>
<h2>Portfolio</h2>
<h3>아직 공사중입니다.</h3>
</body>
</html>

single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>김수영입니다.</title>
</head>
<body>
<nav>
  <a href="/blog/">Blog</a>
  <a href="/about_me/">About me</a>
</nav>

<h1>안녕하세요 김수영입니다</h1>
<h2>대문 페이지</h2>
<h3>아직 만들지 않음</h3>
</body>
</html>